### PR TITLE
feat: tabs component

### LINKED ISSUE #104: Tabs: Create tab component
## Description

Create tab component
https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=6579-45104&mode=design&t=HdC6qfoOLtK4WItH-4

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #104

### CODE REVIEW

**Comment by tewshi** [comment]
@lukicenturi i'm thinking we can add a transition when switching the component.

**Review by tewshi — APPROVED** [review]
lgtm!

**Review by kelsos — CHANGES_REQUESTED** [review]
I have only a minor comment here, other than that things look good.

Thanks

**Review by kelsos — APPROVED** [review]
lgtm

**Pull request merged**
