### PR TITLE
feat: revealable-input

### LINKED ISSUE #38: RevealableTextField: Create component for password input
Create RevealableTextField component, that usually used for password input

- [ ] Extend TextField Component
- [ ] User can toggle between `type=text` and `type=password` by eye button

image

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #38

### CODE REVIEW

**Comment by tewshi** [comment]
not sure why the props are showing here, also the dark mode of the toggle button needs small adjustment
Screenshot 2023-07-12 at 12 21 38

**Comment by lukicenturi** [comment]
> not sure why the props are showing here, also the dark mode of the toggle button needs small adjustment Screenshot 2023-07-12 at 12 21 38
> 
> for the props, I think you should define the expected props of the revealable input and then pass them down to the text field...

updated.
For the props as css variable, that's the way the css module `v-bind` works

**Review by tewshi — APPROVED** [review]
lgtm!

**Review by kelsos — APPROVED** [review]
lgtm

**Pull request merged**
